version: '3'
services:
  elastic_knowledge:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elastic_knowledge
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.watermark.low=3gb
      - cluster.routing.allocation.disk.watermark.high=2gb
      - cluster.routing.allocation.disk.watermark.flood_stage=1gb
    ports:
     - 9200:9200
     - 9300:9300
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 20s
      timeout: 10s
      retries: 5

  search:
    container_name: search
    build: .
    restart: always
    environment:
      FLASK_APP: search
      FLASK_ENV: development
      SECRET_KEY: CHANGE_ME
      ELASTICSEARCH_URL: http://elastic_knowledge:9200
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
     - ./app:/home/search/app
    links:
     - elastic_knowledge
    depends_on:
     - elastic_knowledge
    ports:
     - 5000:5000

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana_knowledge
    environment:
      # SERVER_NAME: kibana.example.org
      # ELASTICSEARCH_HOSTS: http://elasticsearch.example.org
    depends_on:
     - elastic_knowledge