version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    # environment:
    #   -
    ports:
      - 5432:5432
    # volumes:
    # - ./data/mysql:/tmp/data
    # healthcheck:
    # test: ["CMD", "curl", "http://localhost:9200"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 5

  search:
    container_name: search
    build: .
    restart: always
    environment:
      FLASK_APP: search
      FLASK_ENV: development
      SECRET_KEY: CHANGE_ME
      # MYSQL_URL:
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - ./app:/home/search/app
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 5000:5000

      # + nginx 
    nginx:
      image: "nginx:latest"
      container_name: nginx
      # environment:
      #   - CONFIG_PATH:
      ports:
        - 80:80
      # volumes:
      # - ./data/nginx:/etc/nginx/sites-enabled
      # healthcheck:
      # test: ["CMD", "curl", "http://localhost:80"]
      #   interval: 20s
      #   timeout: 10s
      #   retries: 5